[WIP] Implement links (finally only links :D )
danielsaidi/RichTextKit pull request #143
Opened 2024-02-13 16:45 UTC by DominikBucher12

- WIP
- WIP
- WIP 

We will have a nice call with @danielsaidi on how to polish this so we can merge this ASAP :)

2024-03-04 08:35 UTC, danielsaidi commented
@DominikBucher12 Is this ready for review?

2024-03-04 08:37 UTC, DominikBucher12 commented
I think you can review this, so we can merge it soon... But I would say finishing https://github.com/danielsaidi/RichTextKit/pull/154 and https://github.com/danielsaidi/RichTextKit/pull/146 before this is needed more I'd say :)

2024-03-04 08:55 UTC, danielsaidi requested changes

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Actions/RichTextAction.swift
> +    case link(url: URL?)
I'd prefer if we keep the alphabetical order for this enum and all switches over it.

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Actions/RichTextAction.swift
> +        case .link: .actionCopy // TODO: Link
Add this image before merging, just add a `link` image that uses the "link" symbol.

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Attributes/RichTextAttribute+Link.swift
> +    init(link: String, color: ColorRepresentable) {
Can we call this `RichTextLinkAttribute`? 

Also, what are the properties? Is `link` the `url`? If so, by renaming the type as suggested, we could use explicit naming and call this `url` or `urlString`.

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Component/RichTextViewComponent+Link.swift
> +    func unsetLinkFromCurrentRichTextStyle() {
We no longer use the `current` term for the component, so I think renaming this to `removeLink` would be enough.

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Component/RichTextViewComponent+Link.swift
> +    func setCurrentRichTextLink(_ link: URL?) {
And rename this to `addLink(to url: URL?)`?

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Context/RichTextContext+Link.swift
> +    }
Indentation looks off

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Context/RichTextContext.swift
> +    @Published
We should have a new line between the two properties

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Coordinator/RichTextCoordinator.swift
> -        updateTextViewAttributesIfNeeded()
Should this update be removed?

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Coordinator/RichTextCoordinator.swift
> +            if let linkString = textView.richTextAttributes[.link] as? String,
Yes, before approval :)

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Coordinator/RichTextLinkSetter.swift
> +    let textView: NSTextView
You can use the newly pushed `TextViewRepresentable` to avoid having two initializers.

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Coordinator/RichTextLinkSetter.swift
> +    let textView: NSTextView
But since we have the `(textView as? RichTextView)?.renderLinks` cast, why not just require a `RichTextView `?

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Coordinator/RichTextLinkSetter.swift
> +    func textViewDidChange(_ notification: Notification) {
Plus, this is the exact same code twice.

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Images/Image+RichText.swift
> +    static let richTextKindLink = symbol("link")
`richTextLink` is enough :) Place this in alpha order and use it as instructed above 👍

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/RichTextView_UIKit.swift
> +    open func renderLinks(in characterRange: NSRange, at origin: CGPoint) {
These two are almost identical, but should be able to be identical as well, right? If so, can we instead extend the component protocol?

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Styles/PresentationContainer.swift
> +//  PresentationContainer.swift
Regarding placement of the file, this is not a style so it should be elsewhere. Perhaps add a `Presentation` root folder?

2024-03-04 08:55 UTC, danielsaidi commented on Sources/RichTextKit/Styles/RichTextStyle+ToggleGroup.swift
> +        @State private var urlString = ""
The link button should not be part of the styles group.

2024-03-04 08:56 UTC, danielsaidi commented
@DominikBucher12 I have reviewed the PR in its current state. It will be amazing to get link support, but this PR needs a bit more work before we can merge it.

2024-05-16 12:50 UTC, martindufort commented
What's the current status on having `link` support integrate into the `main` branch. Would love to use this...

2024-05-17 09:37 UTC, closed without merging